version: '2'

services:
  joinmarket:
    build:
      context: ./
      dockerfile: Dockerfile-joinmarket
      args:
        VERSION: 0.8.0
    image: joinmarket:0.8.0
    volumes:
      - ./joinmarket/joinmarket.cfg:/jm/scripts/joinmarket.cfg
      - ./joinmarket/wallets:/jm/scripts/wallets
